In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [2]:
df = pd.DataFrame({
    "soil_moist" : [0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,0.45,0.05,0.08,0.27,0.55,0.70,0.12,0.03],
    "temp_c" : [34,30,26,22,28,30,19,22,35,24,33,33,21,25,20,29],
    "sun_hours" : [9,8,7,4,8,10,3,10,12,5,9,11,2,6,1,9],
    "needs_water" : [1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1]
})

In [3]:
df.head()

   soil_moist  temp_c  sun_hours  needs_water
0        0.10      34          9            1
1        0.15      30          8            1
2        0.20      26          7            1
3        0.25      22          4            0
4        0.40      28          8            0

In [4]:
x = df[['soil_moist',	'temp_c',	'sun_hours']]
y = df['needs_water']

In [5]:
x_min = x.min()
x_max = x.max()
x_scaled = (x-x_min) / (x_max - x_min + 1e-8)

In [6]:
x_scaled.head()

   soil_moist  temp_c  sun_hours
0    0.104478  0.9375   0.727273
1    0.179104  0.6875   0.636364
2    0.253731  0.4375   0.545455
3    0.328358  0.1875   0.272727
4    0.552239  0.5625   0.636364

In [7]:
x_train, x_test, y_train, y_test = train_test_split(
    x_scaled, y,
    test_size=0.25,
    random_state=42
    )

In [12]:
model = keras.Sequential([
    layers.Input(shape = (x_train.shape[1],)),
    layers.Dense(8,activation = 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [13]:
model.compile(optimizer='sgd' , loss='binary_crossentropy' , metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [14]:
history = model.fit(
    x_train.values , y_train.values,
    validation_data = (x_test.values,y_test.values),
    epochs = 100,
    batch_size = 4 ,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 175ms/step - accuracy: 0.5833 - loss: 0.7416 - val_accuracy: 0.2500 - val_loss: 0.7889
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.7379 - val_accuracy: 0.2500 - val_loss: 0.7875
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.7367 - val_accuracy: 0.2500 - val_loss: 0.7861
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.7355 - val_accuracy: 0.2500 - val_loss: 0.7848
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.7378 - val_accuracy: 0.2500 - val_loss: 0.7834
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.7347 - val_accuracy: 0.2500 - val_loss: 0.7820
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.7317 - val_accuracy: 0.2500 - val_loss: 0.7808
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.7304 - val_accuracy: 0.2500 - val_loss: 0.7796
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.7291 - val_accuracy: 0.2500 - val_loss: 0.7783
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.7278 - val_accuracy: 0.2500 - val_loss: 0.7772
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.7271 - val_accuracy: 0.2500 - val_loss: 0.7759
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.7260 - val_accuracy: 0.2500 - val_loss: 0.7749
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.7247 - val_accuracy: 0.2500 - val_loss: 0.7738
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.7248 - val_accuracy: 0.2500 - val_loss: 0.7728
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.7225 - val_accuracy: 0.2500 - val_loss: 0.7718
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.7216 - val_accuracy: 0.2500 - val_loss: 0.7707
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.7207 - val_accuracy: 0.2500 - val_loss: 0.7696
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5833 - loss: 0.7206 - val_accuracy: 0.2500 - val_loss: 0.7684
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.7190 - val_accuracy: 0.2500 - val_loss: 0.7672
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.7187 - val_accuracy: 0.2500 - val_loss: 0.7660
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.7171 - val_accuracy: 0.2500 - val_loss: 0.7648
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.7169 - val_accuracy: 0.2500 - val_loss: 0.7636
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.7170 - val_accuracy: 0.2500 - val_loss: 0.7624
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.7146 - val_accuracy: 0.2500 - val_loss: 0.7613
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.7143 - val_accuracy: 0.2500 - val_loss: 0.7601
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.7141 - val_accuracy: 0.2500 - val_loss: 0.7590
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5833 - loss: 0.7123 - val_accuracy: 0.2500 - val_loss: 0.7579
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5833 - loss: 0.7121 - val_accuracy: 0.2500 - val_loss: 0.7568
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.7106 - val_accuracy: 0.5000 - val_loss: 0.7558
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.7099 - val_accuracy: 0.5000 - val_loss: 0.7547
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5833 - loss: 0.7097 - val_accuracy: 0.5000 - val_loss: 0.7537
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.7095 - val_accuracy: 0.5000 - val_loss: 0.7526
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.7072 - val_accuracy: 0.5000 - val_loss: 0.7516
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.7068 - val_accuracy: 0.5000 - val_loss: 0.7505
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.7059 - val_accuracy: 0.5000 - val_loss: 0.7495
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.7063 - val_accuracy: 0.5000 - val_loss: 0.7485
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.7041 - val_accuracy: 0.5000 - val_loss: 0.7476
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.7040 - val_accuracy: 0.5000 - val_loss: 0.7466
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5833 - loss: 0.7030 - val_accuracy: 0.5000 - val_loss: 0.7457
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.7031 - val_accuracy: 0.5000 - val_loss: 0.7448
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.7012 - val_accuracy: 0.5000 - val_loss: 0.7438
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.7032 - val_accuracy: 0.5000 - val_loss: 0.7429
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6997 - val_accuracy: 0.5000 - val_loss: 0.7420
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6992 - val_accuracy: 0.5000 - val_loss: 0.7411
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6995 - val_accuracy: 0.5000 - val_loss: 0.7402
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6977 - val_accuracy: 0.5000 - val_loss: 0.7393
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6971 - val_accuracy: 0.5000 - val_loss: 0.7385
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6978 - val_accuracy: 0.5000 - val_loss: 0.7376
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6957 - val_accuracy: 0.5000 - val_loss: 0.7368
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6963 - val_accuracy: 0.5000 - val_loss: 0.7360
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6943 - val_accuracy: 0.5000 - val_loss: 0.7350
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6936 - val_accuracy: 0.5000 - val_loss: 0.7342
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.7334
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5833 - loss: 0.6927 - val_accuracy: 0.5000 - val_loss: 0.7326
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6918 - val_accuracy: 0.5000 - val_loss: 0.7318
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6925 - val_accuracy: 0.5000 - val_loss: 0.7311
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6904 - val_accuracy: 0.5000 - val_loss: 0.7305
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.6899 - val_accuracy: 0.5000 - val_loss: 0.7298
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6903 - val_accuracy: 0.5000 - val_loss: 0.7291
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6886 - val_accuracy: 0.5000 - val_loss: 0.7285
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6894 - val_accuracy: 0.5000 - val_loss: 0.7279
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6902 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6868 - val_accuracy: 0.5000 - val_loss: 0.7266
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6889 - val_accuracy: 0.5000 - val_loss: 0.7260
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.6866 - val_accuracy: 0.5000 - val_loss: 0.7254
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.6859 - val_accuracy: 0.5000 - val_loss: 0.7249
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6841 - val_accuracy: 0.5000 - val_loss: 0.7242
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6844 - val_accuracy: 0.5000 - val_loss: 0.7237
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6838 - val_accuracy: 0.5000 - val_loss: 0.7231
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6825 - val_accuracy: 0.5000 - val_loss: 0.7226
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6820 - val_accuracy: 0.5000 - val_loss: 0.7221
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5833 - loss: 0.6812 - val_accuracy: 0.5000 - val_loss: 0.7213
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5833 - loss: 0.6818 - val_accuracy: 0.5000 - val_loss: 0.7207
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6800 - val_accuracy: 0.5000 - val_loss: 0.7201
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6794 - val_accuracy: 0.5000 - val_loss: 0.7195
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.6789 - val_accuracy: 0.5000 - val_loss: 0.7188
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.6780 - val_accuracy: 0.5000 - val_loss: 0.7182
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.6774 - val_accuracy: 0.5000 - val_loss: 0.7177
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.6776 - val_accuracy: 0.5000 - val_loss: 0.7171
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6769 - val_accuracy: 0.5000 - val_loss: 0.7165
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6767 - val_accuracy: 0.5000 - val_loss: 0.7158
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.6754 - val_accuracy: 0.5000 - val_loss: 0.7152
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6753 - val_accuracy: 0.5000 - val_loss: 0.7145
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6736 - val_accuracy: 0.5000 - val_loss: 0.7139
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6729 - val_accuracy: 0.5000 - val_loss: 0.7132
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6729 - val_accuracy: 0.5000 - val_loss: 0.7125
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.6715 - val_accuracy: 0.5000 - val_loss: 0.7118
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6711 - val_accuracy: 0.5000 - val_loss: 0.7112
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6705 - val_accuracy: 0.5000 - val_loss: 0.7105
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6697 - val_accuracy: 0.5000 - val_loss: 0.7099
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6692 - val_accuracy: 0.5000 - val_loss: 0.7091
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6687 - val_accuracy: 0.5000 - val_loss: 0.7083
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6683 - val_accuracy: 0.5000 - val_loss: 0.7076
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6682 - val_accuracy: 0.5000 - val_loss: 0.7068
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6668 - val_accuracy: 0.5000 - val_loss: 0.7061
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6673 - val_accuracy: 0.5000 - val_loss: 0.7053
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6657 - val_accuracy: 0.5000 - val_loss: 0.7046
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6649 - val_accuracy: 0.5000 - val_loss: 0.7039
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6672 - val_accuracy: 0.5000 - val_loss: 0.7032
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.6639 - val_accuracy: 0.5000 - val_loss: 0.7025